import Head from "next/head";
import { useState } from "react";


import { api } from "~/utils/api";

export default function Home() {

  const CACHE_KEY = 'edit-survey-unsaved'
  const [postId, setPostId] = useState("")
  const [error, setError] = useState(false)
  const [surveyData, setSurveyData] = useState({
    id: "",
    notes: "",
    createdAt: "",
  })
  const setNotes = (notes: string) => {
    setSurveyData((prev) => ({ ...prev, notes }))
  }
  const [notesStateCache, setNotesStateCache] = useState("")

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">

      </main>
    </>
  );
}
